[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]
